name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Authenticate
      run: dotnet nuget add source https://packages.infragistics.com/nuget/licensed/ -n Infragistics -u api -p "${NUGET_AUTH_TOKEN#api:}" --store-password-in-clear-text
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Set project name
      run: echo "PROJECT_NAME=$(jq -r '.applicationName' .appbuilder-state.json | sed 's/ //g')" >> $GITHUB_ENV
    - name: Update NavigationManager in Razor files
      run: find ${{ env.PROJECT_NAME }} -type f -name "*.razor" -exec sed -i "s|NavigationManager.NavigateTo(path);|NavigationManager.NavigateTo(path.TrimStart('/'));|" {} \;
    - name: Publish Blazor WebAssembly
      run: dotnet publish -c Release -o ./publish
    - name: Update Base Href in index.html
      run: sed -i 's|<base href="/"|<base href="/${{ github.event.repository.name }}/"|' publish/wwwroot/index.html
    - name: SPA Routing Handling
      run: cp publish/wwwroot/index.html publish/wwwroot/404.html
    - name: Upload Build Artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: publish/wwwroot
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1